### ISSUE TITLE
i got error on open setting page

### ISSUE THREAD

**Issue by Srikanth30t** [outer-web/filament-settings#2]
Thanks for you work,
but i got this error
Typed static property Filament\Pages\BasePage::$view must not be accessed before initialization
i am using laravel 
"laravel/framework": "^10.10",
"filament/filament": "3.2",
"outerweb/filament-settings": "^1.1"

thank you

**Comment by SimonBroekaert** [comment]
Hi,

I personally use this package too and have not (yet) had this issue.

Could you show me your created settings page so that I have a bit more context?

Thanks!

**Comment by Srikanth30t** [comment]
i created this page as our document 
https://filamentphp.com/plugins/outerweb-settings

App\Filament\Pages\Settings/Settings.php
<?php

namespace App\Filament\Pages\Settings;

use Closure;
use Filament\Forms\Components\Tabs;
use Filament\Forms\Components\TextInput;
use Outerweb\FilamentSettings\Filament\Pages\Settings as BaseSettings;

class Settings extends BaseSettings
{
    public function schema(): array|Closure
    {
        return [
            Tabs::make('Settings')
                ->schema([
                    Tabs\Tab::make('General')
                        ->schema([
                            TextInput::make('general.brand_name')
                                ->required(),
                        ]),
                    Tabs\Tab::make('Seo')
                        ->schema([
                            TextInput::make('seo.title')
                                ->required(),
                            TextInput::make('seo.description')
                                ->required(),
                        ]),
                ]),
        ];
    }
}
--------------------------

in your document
use OuterWeb\FilamentSettings\Filament\FilamentSettings; 
please replace 
use Outerweb\FilamentSettings\Filament\Plugins\FilamentSettingsPlugin;

![Screenshot 2024-03-18 180618](https://github.com/outer-web/filament-settings/assets/13825784/53d41902-29d0-4080-bb84-4d2627991f48)

thank you for your fast reply 
correct me if I'm wrong.

**Comment by webmaster254** [comment]
Hi,
I got the same error
Typed static property Filament\Pages\BasePage::$view must not be accessed before initialization

**Comment by SimonBroekaert** [comment]
Hello @Srikanth30t and @webmaster254 ,

I have fixed the problem in the README.md where the wrong use statement was described.

Could you try again based on [these changes](https://github.com/outer-web/filament-settings/commit/d5ebfd1f6d1525a2185305f94e75670328519224) and let me know if the problem still exists?

If it does, could you send me your FilamentServiceProvider and custom settings page file contents?

Thank you!

**Comment by Srikanth30t** [comment]
Hi, 
i done above changes but still get error 
![image](https://github.com/outer-web/filament-settings/assets/13825784/d51388dd-b7ef-480f-a8b9-dca298650ca5)
FilamentServiceProvider and custom settings page
![image](https://github.com/outer-web/filament-settings/assets/13825784/82ae6d98-4aa3-418c-b4d0-ade3aae417f5)

Thank you.

**Comment by SimonBroekaert** [comment]
Hi @Srikanth30t ,

Thank you for your patience in this as I still cannot reproduce it on my end.

I have changed the code in **v1.2.0** so that the typed static property `$view` is now set directly instead of overriding the Filament `getView()` method. This should in theory fix the error where it is complaining that the code is trying to access the `$view` property while it is not yet set to a specific value.

Please let me know if it fixes the issue for you.

Thanks!

**Comment by Srikanth30t** [comment]
Hi @SimonBroekaert,

Thank you for your effort in solving this issue, 

I am waiting for your version 1.2.0

Thanks.

**Comment by Srikanth30t** [comment]
Hi @SimonBroekaert 
Thank you so much it's working...
